# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'marketing_attribution'
version: "1.0.0"
profile: "marketing_attribution"

model-paths: ["models"]
seed-paths: ["seeds"]
clean-targets: ["target", "dbt_packages"]

models:
  marketing_attribution:
    +materialized: view
    staging:
      +schema: raw
    intermediate:
      +schema: analytics
    marts:
      +schema: analytics
      +materialized: table

flags:
  partial_parse: false

  require_generic_test_arguments_property: true
snapshots:
  +schema: snapshots



